server
{
	listen 7860;

	location /engine/ {
		proxy_pass http://127.0.0.1:8000;
		proxy_read_timeout 120s;
		proxy_connect_timeout 120s;
		proxy_send_timeout 120s;
	}

	location / {
		proxy_pass http://127.0.0.1:3000;
	}
}